# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-08 23:28
from __future__ import unicode_literals

import addresses.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('address', models.CharField(max_length=255, unique=True, validators=[addresses.validators.validate_address])),
            ],
            options={
                'managed': True,
            },
        ),
    ]
