# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-20 13:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='address',
            new_name='location',
        ),
    ]
